services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd backend && npm install && node src/index.js"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "cd frontend && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:5173"

  sfu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sfu:/app/sfu
    command: sh -c "cd sfu && npm install && node src/server.js"
    ports:
      - "3001:3001"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videocall
    ports:
      - "5432:5432"
