name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # backend
      - name: Cache backend modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-
      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend

      # frontend
      - name: Cache frontend modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-
      - name: Configure npm for retries
        run: |
          npm config set fetch-retries 5
          npm config set registry https://registry.npmjs.org/
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      # sfu
      - name: Cache sfu modules
        uses: actions/cache@v3
        with:
          path: sfu/node_modules
          key: ${{ runner.os }}-sfu-${{ hashFiles('sfu/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-sfu-
      - name: Install sfu dependencies
        run: npm ci
        working-directory: ./sfu
