name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリ取得
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Hub ログイン（GitHub Secrets 必要）
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Backend ビルド & プッシュ
      - name: Build & Push Backend
        run: |
          docker build \
            -t docker.io/remi012/videocall-backend:${{ github.sha }} \
            -f ./backend/Dockerfile ./backend
          docker push docker.io/remi012/videocall-backend:${{ github.sha }}

      # 4. Frontend ビルド & プッシュ
      - name: Build & Push Frontend
        run: |
          docker build \
            -t docker.io/remi012/videocall-frontend:${{ github.sha }} \
            -f ./frontend/Dockerfile ./frontend
          docker push docker.io/remi012/videocall-frontend:${{ github.sha }}

      # 5. SFU ビルド & プッシュ（修正ポイント）
      - name: Build & Push SFU
        run: |
          docker build \
            -t docker.io/remi012/videocall-sfu:${{ github.sha }} \
            -f ./sfu/Dockerfile ./sfu
          docker push docker.io/remi012/videocall-sfu:${{ github.sha }}

  deploy:
    name: Helm Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリ再取得
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Helm セットアップ
      - name: Setup Helm
        uses: azure/setup-helm@v3

      # 3. Helm デプロイ
      - name: Deploy with Helm
        run: |
          helm upgrade --install videocall ./infra/helm-chart \
            --set image.backend.repository=docker.io/remi012/videocall-backend \
            --set image.backend.tag=${{ github.sha }} \
            --set image.frontend.repository=docker.io/remi012/videocall-frontend \
            --set image.frontend.tag=${{ github.sha }} \
            --set image.sfu.repository=docker.io/remi012/videocall-sfu \
            --set image.sfu.tag=${{ github.sha }}
